unbind C-b
set -g prefix M-m
bind -n M-m send-prefix

bind r source-file ~/.tmux.conf
bind M-m run-shell -b "/home/igorr/.dotfiles/bin/tmux-session-switch"

# tmux for some reason spawns login shells by default
# this should override that curious default
set -g default-command "${SHELL}"

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g set-titles on
# set -g set-titles-string '#{session_name}: #{pane_title}'

# override another ancient default
set -s escape-time 10

set -g focus-events on
set -g allow-rename on
set -g mouse on

# by default tmux starts window numbers from zero :)
set -g base-index 1
set -g renumber-windows on

# set -g status-style bg=default
# set -g status-left-length 99
# set -g status-right-length 99
# set -g status-justify absolute-centre

# Needed for Pi TUI modified Enter keys inside tmux.
set -g extended-keys on
set -g extended-keys-format csi-u

# split windows like vim
# vim's definition of a horizontal/vertical split is reversed from tmux's
bind s split-window -v
bind v split-window -h

# move around panes with hjkl, as one would in vim after pressing ctrl-w
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize panes like vim
# feel free to change the "1" to however many lines you want to resize by, only
# one at a time can be slow
bind < resize-pane -L 1
bind > resize-pane -R 1
bind - resize-pane -D 1
bind + resize-pane -U 1
